#include "dee_config_gen_ffi.h"

#include <stdio.h>
#include <string.h>

static DcgStringView make_string_view(const char *value) {
  DcgStringView view;
  view.ptr = (const uint8_t *)value;
  view.len = strlen(value);
  return view;
}

static int print_error_and_cleanup(const char *label, DcgStatusCode code, DcgError *err) {
  fprintf(
      stderr,
      "%s failed: code=%u, msg=%.*s\n",
      label,
      (unsigned)code,
      (int)err->message.len,
      (const char *)err->message.ptr);
  dcg_free_error(err);
  return 1;
}

int main(void) {
  const char *job_text =
      "template_id: atmos_ec3_v1\n"
      "profile: standard\n"
      "job_mode: single\n"
      "encode_mode: streaming\n"
      "input:\n"
      "  storage_path: ./input\n"
      "  file_names: [testADM.wav]\n"
      "output:\n"
      "  storage_path: ./output\n"
      "  file_names: [output.ec3]\n"
      "misc:\n"
      "  temp_dir: ./tmp\n";

  if (dcg_abi_version() != 1U) {
    fprintf(stderr, "unexpected ABI version: %u\n", dcg_abi_version());
    return 1;
  }

  DcgError err = {0};
  DcgValidateOutput validated = {0};
  DcgStatusCode code =
      dcg_validate_job(make_string_view(job_text), NULL, &validated, &err);
  if (code != DCG_STATUS_OK) {
    return print_error_and_cleanup("validate", code, &err);
  }

  printf(
      "validated: template=%.*s mode=%.*s\n",
      (int)validated.template_id.len,
      (const char *)validated.template_id.ptr,
      (int)validated.encode_mode.len,
      (const char *)validated.encode_mode.ptr);
  dcg_free_validate_output(&validated);
  dcg_free_error(&err);

  DcgGenerateOptions options = {0};
  options.format = DCG_RENDER_FORMAT_XML;

  DcgGenerateOutput generated = {0};
  code = dcg_generate_config(make_string_view(job_text), &options, &generated, &err);
  if (code != DCG_STATUS_OK) {
    return print_error_and_cleanup("generate", code, &err);
  }

  printf("generated bytes=%zu\n", generated.rendered_config.len);
  dcg_free_generate_output(&generated);
  dcg_free_error(&err);
  return 0;
}
