#[derive(Debug, Clone)]
pub struct PcmDdpV1Filter {
    pub metering_mode: String,
    pub dialogue_intelligence: bool,
    pub speech_threshold: u8,
    pub data_rate: u16,
    pub bitstream_mode: String,
    pub downmix_config: String,
    pub timecode_frame_rate: String,
    pub start: String,
    pub end: String,
    pub time_base: String,
    pub prepend_silence_duration: String,
    pub append_silence_duration: String,
    pub lfe_on: bool,
    pub dolby_surround_mode: String,
    pub dolby_surround_ex_mode: String,
    pub user_data: i32,
    pub line_mode_drc_profile: String,
    pub rf_mode_drc_profile: String,
    pub lfe_lowpass_filter: bool,
    pub surround_90_degree_phase_shift: bool,
    pub surround_3db_attenuation: bool,
    pub loro_center_mix_level: String,
    pub loro_surround_mix_level: String,
    pub ltrt_center_mix_level: String,
    pub ltrt_surround_mix_level: String,
    pub preferred_downmix_mode: String,
    pub allow_hybrid_downmix: bool,
    pub starting_timecode: String,
    pub frame_rate: String,
    pub custom_dialnorm: i8,
    pub encoder_mode: String,
}
