#ifndef DEE_CONFIG_GEN_FFI_H
#define DEE_CONFIG_GEN_FFI_H

/* This file is generated by cbindgen. Do not edit manually. */

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#define DCG_FFI_ABI_VERSION 1
#define DCG_FFI_HEADER_VERSION 10100
#define DCG_FFI_HEADER_VERSION_STR "1.1.0"

#define DCG_STATUS_OK DCG_STATUS_CODE_OK
#define DCG_STATUS_INVALID_ARGUMENT DCG_STATUS_CODE_INVALID_ARGUMENT
#define DCG_STATUS_PARSE_ERROR DCG_STATUS_CODE_PARSE_ERROR
#define DCG_STATUS_RESOLVE_ERROR DCG_STATUS_CODE_RESOLVE_ERROR
#define DCG_STATUS_RENDER_ERROR DCG_STATUS_CODE_RENDER_ERROR
#define DCG_STATUS_INTERNAL_ERROR DCG_STATUS_CODE_INTERNAL_ERROR
#define DCG_STATUS_PANIC DCG_STATUS_CODE_PANIC

#define DCG_RENDER_FORMAT_XML DcgRenderFormat_XML
#define DCG_RENDER_FORMAT_JSON DcgRenderFormat_JSON


enum DcgStatusCode {
  DCG_STATUS_CODE_OK = 0,
  DCG_STATUS_CODE_INVALID_ARGUMENT = 1,
  DCG_STATUS_CODE_PARSE_ERROR = 2,
  DCG_STATUS_CODE_RESOLVE_ERROR = 3,
  DCG_STATUS_CODE_RENDER_ERROR = 4,
  DCG_STATUS_CODE_INTERNAL_ERROR = 5,
  DCG_STATUS_CODE_PANIC = 6,
};
typedef uint32_t DcgStatusCode;

typedef struct DcgStringView {
  const uint8_t *ptr;
  size_t len;
} DcgStringView;

typedef struct DcgResolveOptions {
  bool has_template_override;
  struct DcgStringView template_override;
  bool allow_fixed_override;
  uint8_t windows_drive;
} DcgResolveOptions;

typedef struct DcgOwnedString {
  uint8_t *ptr;
  size_t len;
} DcgOwnedString;

typedef struct DcgValidateOutput {
  struct DcgOwnedString template_id;
  struct DcgOwnedString profile;
  struct DcgOwnedString job_mode;
  struct DcgOwnedString encode_mode;
  struct DcgOwnedString output_container;
} DcgValidateOutput;

typedef struct DcgError {
  DcgStatusCode code;
  struct DcgOwnedString message;
} DcgError;

typedef uint32_t DcgRenderFormat;
#define DcgRenderFormat_XML 0
#define DcgRenderFormat_JSON 1

typedef struct DcgGenerateOptions {
  struct DcgResolveOptions resolve;
  DcgRenderFormat format;
} DcgGenerateOptions;

typedef struct DcgGenerateOutput {
  struct DcgOwnedString rendered_config;
  DcgRenderFormat format;
  struct DcgOwnedString template_id;
  struct DcgOwnedString output_container;
} DcgGenerateOutput;

uint32_t dcg_abi_version(void);

DcgStatusCode dcg_validate_job(struct DcgStringView job,
                               const struct DcgResolveOptions *options,
                               struct DcgValidateOutput *out,
                               struct DcgError *err);

DcgStatusCode dcg_generate_config(struct DcgStringView job,
                                  const struct DcgGenerateOptions *options,
                                  struct DcgGenerateOutput *out,
                                  struct DcgError *err);

void dcg_free_string(struct DcgOwnedString *value);

void dcg_free_validate_output(struct DcgValidateOutput *out);

void dcg_free_generate_output(struct DcgGenerateOutput *out);

void dcg_free_error(struct DcgError *err);

#endif  /* DEE_CONFIG_GEN_FFI_H */
